name: Lint and Test

on:
  pull_request:
    branches:
      - master
      - beta

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 12.x
      - name: npm install and build
        run: |
          npm ci
          npm run build
        env:
          CI: true
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 12.x
      - name: npm install and lint
        run: |
          npm ci
          npm run lint
        env:
          CI: true
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 12.x
      - name: npm install and test
        run: |
          npm ci
          npm test
        env:
          CI: true
